// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWBQ0DwZxpzeSR9ZwM-InNb6dhn3E4xNo',
    appId: '1:156623633534:web:2c41d045c952e12f062c2f',
    messagingSenderId: '156623633534',
    projectId: 'carnet-de-voyage-20c9a',
    authDomain: 'carnet-de-voyage-20c9a.firebaseapp.com',
    databaseURL: 'https://carnet-de-voyage-20c9a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carnet-de-voyage-20c9a.appspot.com',
    measurementId: 'G-XFHCB5JGH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbeZ195DEObRCvPCXRDJRJU3nlrQqnG_0',
    appId: '1:156623633534:android:9c9d64ef8633cf27062c2f',
    messagingSenderId: '156623633534',
    projectId: 'carnet-de-voyage-20c9a',
    databaseURL: 'https://carnet-de-voyage-20c9a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carnet-de-voyage-20c9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7sFJoBVGdXnSHjx46mFBZWzWXGjmWadI',
    appId: '1:156623633534:ios:2d8fa26742e48c19062c2f',
    messagingSenderId: '156623633534',
    projectId: 'carnet-de-voyage-20c9a',
    databaseURL: 'https://carnet-de-voyage-20c9a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'carnet-de-voyage-20c9a.appspot.com',
    androidClientId: '156623633534-0f0ugpqd9q19vg0mn2j4uc9u572r77lk.apps.googleusercontent.com',
    iosClientId: '156623633534-n35vlmu3df6hq17smlciv5av9546c3ok.apps.googleusercontent.com',
    iosBundleId: 'com.example.nomadnotes',
  );

}